import type { Metadata } from "next";
import { Urbanist } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from '@clerk/nextjs';
import Footer from "@/components/footer";
import Navbar from "@/components/navbar";
import ModalProvider from "@/providers/model-provider";
import { ToasterProvider } from "@/providers/taost-provider";

const font = Urbanist({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "HEKSTORE",
  description: "Generated by Saif",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
    <html lang="en">
      <body className={font.className}>
        <ModalProvider/>
        <ToasterProvider/>
        <Navbar/>
        {children}
        <Footer/>
        </body>
    </html>
    </ClerkProvider>
    
  );
}
